apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-provisioning-portal
  labels:
    app: infrastructure-provisioning-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrastructure-provisioning-portal
  template:
    metadata:
      labels:
        app: infrastructure-provisioning-portal
    spec:
      containers:
        - name: api
          image: infrastructure-provisioning-portal:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: infrastructure-provisioning-portal
spec:
  selector:
    app: infrastructure-provisioning-portal
  ports:
    - port: 80
      targetPort: 8080
